"""empty message

Revision ID: fc67ed4731c5
Revises: 
Create Date: 2023-06-01 15:41:24.358805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc67ed4731c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemontypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('types', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('imageURL', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.Column('moves', sa.String(), nullable=False),
    sa.Column('encounterRate', sa.Float(), nullable=True),
    sa.Column('catchRate', sa.Float(), nullable=True),
    sa.Column('captured', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['typeId'], ['pokemontypes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('number')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=True),
    sa.Column('imageURL', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('pokemonId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemonId'], ['pokemons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('pokemons')
    op.drop_table('pokemontypes')
    # ### end Alembic commands ###
